"""add user auth roles and inspectors to certifications

Revision ID: 019695f0ffda
Revises: c6d04b12b67d
Create Date: 2026-06-03 10:03:28.918384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "019695f0ffda"
down_revision: str | Sequence[str] | None = "c6d04b12b67d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(length=80), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "INSPECTOR", "REVIEWER", "VIEWER", name="role_enum"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.add_column(
        "certifications", sa.Column("inspector_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_certifications_inspector_id_users"),
        "certifications",
        "users",
        ["inspector_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_certifications_inspector_id_users"),
        "certifications",
        type_="foreignkey",
    )
    op.drop_column("certifications", "inspector_id")
    op.drop_table("users")
    # ### end Alembic commands ###
