"""align finding attachment foreign keys

Revision ID: c6d04b12b67d
Revises: 7c6a0b8f4d2e
Create Date: 2026-06-03 09:50:06.656503

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6d04b12b67d"
down_revision: str | Sequence[str] | None = "7c6a0b8f4d2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_finding_attachments_finding_id_id_certification_id_certifica"),
        "finding_attachments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_finding_attachments_attachment_id_id_certification_id_certif"),
        "finding_attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_finding_attachments_finding_id_id_certification_id_certifica",
        "finding_attachments",
        "findings",
        ["finding_id", "certification_id"],
        ["id", "certification_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_finding_attachments_attachment_id_id_certification_id_certif",
        "finding_attachments",
        "attachments",
        ["attachment_id", "certification_id"],
        ["id", "certification_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_finding_attachments_certification_id_certifications"),
        "finding_attachments",
        "certifications",
        ["certification_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_finding_attachments_certification_id_certifications"),
        "finding_attachments",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_finding_attachments_attachment_id_id_certification_id_certif",
        "finding_attachments",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_finding_attachments_finding_id_id_certification_id_certifica",
        "finding_attachments",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_finding_attachments_attachment_id_id_certification_id_certif"),
        "finding_attachments",
        "attachments",
        ["attachment_id", "certification_id"],
        ["id", "certification_id"],
    )
    op.create_foreign_key(
        op.f("fk_finding_attachments_finding_id_id_certification_id_certifica"),
        "finding_attachments",
        "findings",
        ["finding_id", "certification_id"],
        ["id", "certification_id"],
    )
    # ### end Alembic commands ###
